import { z } from "zod"

export const VolumioPlayerStateSchema = z.object({
  status: z.enum(["play", "pause"]),
  position: z.number(),
  title: z.string(),
  artist: z.string(),
  album: z.string(),
  albumart: z.string(),
  uri: z.string(),
  trackType: z.string(),
  seek: z.number(),
  duration: z.number(),
  samplerate: z.string(),
  channels: z.number(),
  bitrate: z.number().or(z.null()),
  random: z.null(),
  repeat: z.boolean(),
  repeatSingle: z.boolean(),
  consume: z.boolean(),
  volume: z.number(),
  dbVolume: z.number().or(z.null()),
  mute: z.boolean(),
  disableVolumeControl: z.boolean(),
  stream: z.boolean(),
  updatedb: z.boolean(),
  volatile: z.boolean(),
  service: z.string(),
})
